'use strict';
const E=TunnelEngine, $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,n=4)=>Number(v).toFixed(n), pct=v=>fmt(v*100,2)+'%';
const colors=['#516873','#0b9b84','#2783b3','#dfaa35','#d77942'];
const state={input:{...TunnelExampleCases[5]},schedule:E.baselineSchedule(),horizon:198.2,batch:[],batchResults:[],page:'assess',batchPage:0,dirty:false,scenarioName:'Same as baseline'};
let toastTimer;
function toast(message,error=false){$('#toast').textContent=message;$('#toast').className='visible'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').className='',error?6500:3000);}
function safe(fn){return async (...args)=>{try{return await fn(...args);}catch(e){toast(e.message,true);console.error(e);}};}
function cleanName(s){return String(s).replace(/[\\/:*?"<>|\x00-\x1f]/g,'_').slice(0,70)||'Segment';}
async function download(name,text,mime='text/plain;charset=utf-8'){
 if(globalThis.desktop){const result=await desktop.saveFile({name,text,mime});if(result?.error)throw Error(result.error);if(result?.saved)toast('Saved: '+name);return;}
 const url=URL.createObjectURL(new Blob([text],{type:mime})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Exported: '+name);
}
function updateRockLabel(){const c=$('#input-form').elements.rock_class.value;$('#rock-modulus').textContent='Deformation modulus E = '+E.ROCK[c]+' GPa';}
function fillForm(x){for(const k of ['id',...Object.keys(E.LIMITS),'rock_class'])$('#input-form').elements[k].value=x[k];updateRockLabel();}
function readForm(){const f=$('#input-form'),x={id:f.elements.id.value.trim(),rock_class:f.elements.rock_class.value};if(!x.id)throw Error('Enter a segment ID');for(const k of Object.keys(E.LIMITS)){const raw=f.elements[k].value;if(raw==='')throw Error(E.LABELS[k]+' is required');x[k]=Number(raw);}return E.validateInput(x);}
function requireCurrent(){if(state.dirty)throw Error('Inputs have changed. Select Calculate Assessment first.');}
function badge(i){return `<span class="badge ds${i}">DS${i} ${E.NAMES[i]}</span>`;}
function metric(label,value,note,primary=false){return `<div class="metric-card${primary?' primary-metric':''}"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`;}
function svgHead(w,h,label){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label)}" style="font-family:-apple-system,BlinkMacSystemFont,'PingFang SC',sans-serif">`;}
function probabilitySVG(p){const w=360,h=242,left=37,top=24,bottom=192,pw=309;let s=svgHead(w,h,'Damage-state probability chart for DS0 to DS4');for(let i=0;i<=4;i++){const v=i/4,y=bottom-v*(bottom-top);s+=`<line x1="${left}" y1="${y}" x2="350" y2="${y}" stroke="#e9eeee"/><text x="29" y="${y+4}" text-anchor="end" fill="#8b9ba3" font-size="9">${v*100}%</text>`;}p.forEach((v,i)=>{const x=left+12+i*pw/5,y=bottom-v*(bottom-top);s+=`<rect x="${x}" y="${y}" width="34" height="${bottom-y}" rx="3" fill="${colors[i]}"/><text x="${x+17}" y="${y-7}" text-anchor="middle" font-size="10" fill="#344e5d">${fmt(v*100,1)}%</text><text x="${x+17}" y="213" text-anchor="middle" font-size="10" fill="#697f89">DS${i}</text>`;});return s+'</svg>';}
function recoverySVG(series,T,w=560,h=285){
 const left=48,right=w-16,top=20,bottom=h-49,x=t=>left+t/T*(right-left),y=q=>bottom-q*(bottom-top);let s=svgHead(w,h,'Expected structural performance recovery over time');
 for(let i=0;i<=5;i++){const q=i/5;s+=`<line x1="${left}" x2="${right}" y1="${y(q)}" y2="${y(q)}" stroke="#e8eeee"/><text x="${left-10}" y="${y(q)+4}" text-anchor="end" fill="#81949d" font-size="10">${q.toFixed(1)}</text>`;}
 for(let i=0;i<=4;i++){const t=T*i/4,xx=x(t);s+=`<text x="${xx}" y="${bottom+19}" text-anchor="middle" fill="#81949d" font-size="10">${fmt(t,1)}</text>`;}
 s+=`<text x="${left}" y="11" font-size="9" fill="#738893">Expected performance</text><text x="${(left+right)/2}" y="${h-7}" text-anchor="middle" font-size="10" fill="#738893">Time after defect confirmation (days)</text>`;
 series.forEach(({points,color,dashed})=>{let path=`M${x(points[0].t)},${y(points[0].q)}`;for(let i=1;i<points.length;i++)path+=`H${x(points[i].t)}V${y(points[i].q)}`;s+=`<path d="${path}" fill="none" stroke="${color}" stroke-width="2.7" stroke-linejoin="round"${dashed?' stroke-dasharray="6 3"':''}/>`;});return s+'</svg>';
}
function refreshAssess(){const r=E.assess(state.input,E.baselineSchedule(),state.horizon);state.result=r;$('#result-context').textContent=state.input.id+' · Calculated inputs';$('#metrics').innerHTML=metric('Minimum relative safety factor ζₘᵢₙ',fmt(r.zeta),`Point prediction · DS${r.ds} ${E.NAMES[r.ds]}`,true)+metric('Composite defect intensity η',fmt(r.eta),'Based on angular void extent and deterioration')+metric('Structural resilience index Rₛ',fmt(r.Rs),`Assessment period ${fmt(state.horizon,1)} days`);$('#probability-chart').innerHTML=probabilitySVG(r.probabilities);$('#recovery-chart').innerHTML=recoverySVG([{points:E.history(r.probabilities,E.baselineSchedule(),state.horizon),color:'#087f84'}],state.horizon,360,242);$('#recovery-note').textContent=`Weighted by DS0–DS4 probabilities. Initial performance ${fmt(r.initial,3)}; final recovery level ${fmt(r.final,3)}.`;$('#interpretation').innerHTML=`${esc(state.input.id)}  has a predicted safety factor of  <strong>${fmt(r.zeta)}</strong>, corresponding to  <strong>DS${r.ds} (${E.NAMES[r.ds]})</strong>. Composite defect intensity is  <strong>${fmt(r.eta)}</strong>. Using the state probabilities and baseline repair plan, resilience over the assessment period is  <strong>${fmt(r.Rs)}</strong>.`;$('#inline-metrics').innerHTML=`<div>P(DS3 + DS4)<strong>${pct(r.probabilities[3]+r.probabilities[4])}</strong></div><div>Rock deformation modulus<strong>${E.ROCK[state.input.rock_class]} GPa</strong></div><div>Assessment period<strong>${fmt(state.horizon,1)} days</strong></div>`;const s=E.baselineSchedule();$('#state-table').innerHTML='<table><thead><tr><th>State</th><th>Probability</th><th>Waiting / days</th><th>Repair / days</th><th>Final performance</th><th>State resilience</th></tr></thead><tbody>'+r.probabilities.map((p,i)=>`<tr><td>${badge(i)}</td><td>${pct(p)}</td><td>${fmt(s.wait[i],1)}</td><td>${fmt(s.durations[i].reduce((a,b)=>a+b,0),1)}</td><td>${fmt(E.FINAL[i],2)}</td><td>${fmt(r.stateResilience[i])}</td></tr>`).join('')+'</tbody></table>';$('#input-status').className='form-status';$('#input-status').textContent='Assessment complete · Results match the inputs above';}
function refreshCompare(){
 const baseline=E.assess(state.input,E.baselineSchedule(),state.horizon),adjusted=E.assess(state.input,state.schedule,state.horizon),delta=adjusted.Rs-baseline.Rs;state.adjusted=adjusted;
 $('#compare-context').textContent=state.input.id+' · Expected recovery';$('#compare-chart').innerHTML=recoverySVG([{points:E.history(baseline.probabilities,E.baselineSchedule(),state.horizon),color:'#087f84'},{points:E.history(adjusted.probabilities,state.schedule,state.horizon),color:'#dc883c',dashed:true}],state.horizon);
 $('#compare-metrics').innerHTML=`<div><span>Baseline resilience</span><strong>${fmt(baseline.Rs)}</strong></div><div><span>Adjusted resilience</span><strong>${fmt(adjusted.Rs)}</strong></div><div><span>Absolute change ΔRₛ</span><strong class="gain">${delta>=0?'+':''}${fmt(delta)}</strong></div>`;
 const last=Math.max(...state.schedule.durations.map((a,i)=>state.schedule.wait[i]+a.reduce((x,y)=>x+y,0)));
 $('#comparison-note').textContent=`${state.scenarioName}. Relative change ${delta>=0?'+':''}${fmt(delta/baseline.Rs*100,2)}%. Expected final performance of the adjusted plan ${fmt(adjusted.final,3)}.`+(last>state.horizon+1e-9?`  Some stages finish after the assessment period; Rₛ is integrated only up to day ${fmt(state.horizon,1)}  days.`:'');
 updateStageTotal();
}
function stageEditor(){const i=Number($('#stage-state').value);$('#stage-editor').innerHTML=`<label class="wait-input">Waiting time (days)<input aria-label="DS${i} Waiting time" data-wait="${i}" type="number" min="0" max="3650" step="any" value="${state.schedule.wait[i]}"></label><div class="muted" style="font-size:10px">Stage / Gain fraction · Duration (days)</div>`+E.STAGES[i].map((s,k)=>`<div class="stage-row"><div><strong>${s[0]} · ${esc(s[1])}</strong><small>Gain fraction ${pct(s[3])} · Baseline ${s[2]} days</small></div><label><input aria-label="DS${i} ${s[0]} Stage duration" data-stage="${k}" type="number" min="0" max="3650" step="any" value="${fmt(state.schedule.durations[i][k],3).replace(/\.?0+$/,'')||'0'}"></label></div>`).join('')+'<p id="stage-total" class="stage-total"></p>';updateStageTotal();}
function updateStageTotal(){const i=Number($('#stage-state').value),sum=state.schedule.durations[i].reduce((a,b)=>a+b,0),el=$('#stage-total');if(el)el.textContent=`Repair duration ${fmt(sum,1)}  days · Including waiting ${fmt(sum+state.schedule.wait[i],1)}  days · Final performance ${fmt(E.FINAL[i],2)}`;}
function computeBatch(){const ar=E.stateResilience(state.schedule,state.horizon);state.batchResults=state.batch.map(x=>{const r=E.assess(x,E.baselineSchedule(),state.horizon);r.adjustedRs=r.probabilities.reduce((a,v,i)=>a+v*ar[i],0);return r;});state.batchPage=0;renderBatch();}
function renderBatch(){const all=state.batchResults;$('#batch-count').textContent=`Segments · ${all.length}`;if(!all.length){$('#batch-summary').innerHTML='';$('#batch-table').innerHTML='<div class="empty">Load the case segments or import your segment CSV file.</div>';$('#batch-page-label').textContent='0 / 0';$('#prev-page').disabled=$('#next-page').disabled=true;return;}
 const avg=all.reduce((a,b)=>a+b.Rs,0)/all.length,low=all.reduce((a,b)=>a.Rs<b.Rs?a:b),severe=all.filter(r=>r.ds>=3).length;$('#batch-summary').innerHTML=metric('Segments assessed',all.length,'Baseline plan · '+fmt(state.horizon,1)+' days')+metric('Mean resilience',fmt(avg),'Based on η-conditional probabilities for each segment')+metric('Lowest resilience',fmt(low.Rs),esc(low.input.id))+metric('Point prediction DS3 / DS4',severe+' <small> segments</small>','Classified by minimum relative safety factor');
 const q=$('#batch-search').value.toLowerCase();let rows=all.filter(r=>r.input.id.toLowerCase().includes(q));const sort=$('#batch-sort').value;if(sort==='resilience')rows.sort((a,b)=>a.Rs-b.Rs);if(sort==='safety')rows.sort((a,b)=>a.zeta-b.zeta);let pages=Math.ceil(rows.length/50);state.batchPage=Math.min(state.batchPage,Math.max(pages-1,0));$('#batch-page-label').textContent=`${pages?state.batchPage+1:0} / ${pages} · ${rows.length}  segments`;$('#prev-page').disabled=state.batchPage===0;$('#next-page').disabled=state.batchPage+1>=pages;
 $('#batch-table').innerHTML=rows.length?'<table><thead><tr><th>Segment</th><th>Rock class</th><th>ζₘᵢₙ</th><th>Predicted state</th><th>η</th><th>P(DS3 + DS4)</th><th>Baseline Rₛ</th><th>Adjusted Rₛ</th><th></th></tr></thead><tbody>'+rows.slice(state.batchPage*50,(state.batchPage+1)*50).map(r=>`<tr><td>${esc(r.input.id)}</td><td>${r.input.rock_class}</td><td>${fmt(r.zeta)}</td><td>${badge(r.ds)}</td><td>${fmt(r.eta)}</td><td>${pct(r.probabilities[3]+r.probabilities[4])}</td><td><strong>${fmt(r.Rs)}</strong></td><td>${fmt(r.adjustedRs??r.Rs)}</td><td><button class="text-button" data-open-case="${all.indexOf(r)}">View →</button></td></tr>`).join('')+'</tbody></table>':'<div class="empty">No matching segments found.</div>';
}
function go(page){if(page==='compare')requireCurrent();state.page=page;$$('.page').forEach(el=>el.hidden=el.id!=='page-'+page);$$('.nav').forEach(el=>el.classList.toggle('active',el.dataset.page===page));$('#breadcrumb').textContent='Workspace / '+{assess:'Segment Assessment',compare:'Repair Comparison',batch:'Batch Assessment',tasks:'Repair Task Library'}[page];if(page==='compare'){refreshCompare();stageEditor();}window.scrollTo(0,0);}
function calculate(){state.input=readForm();state.dirty=false;refreshAssess();refreshCompare();}
function setPreset(name,fn){state.schedule=E.baselineSchedule();fn(state.schedule);state.scenarioName=name;stageEditor();refreshCompare();}
const HEADERS=['id','theta','omega','d','l','D','H','lambda','rock_class'];
function exportBatch(){if(!state.batchResults.length)throw Error('Load batch data first');const rows=[['id','theta','omega','d','l','D','H','lambda','rock_class','E_GPa','zeta_min','point_damage_state','eta','P_DS0','P_DS1','P_DS2','P_DS3','P_DS4','Rs_baseline','Rs_adjusted','horizon_d'],...state.batchResults.map(r=>[...HEADERS.map(k=>r.input[k]),E.ROCK[r.input.rock_class],r.zeta,'DS'+r.ds,r.eta,...r.probabilities,r.Rs,r.adjustedRs??r.Rs,state.horizon])];return download('batch-assessment-results.csv',E.toCSV(rows),'text/csv;charset=utf-8');}
function project(){requireCurrent();return {format:'tunnel-resilience-project',version:1,modelVersion:TunnelModelData.version,checkpoint:TunnelModelData.checkpoint_sha256,input:state.input,horizon:state.horizon,schedule:state.schedule,scenarioName:state.scenarioName,batch:state.batch};}
function importProject(p){if(p?.format!=='tunnel-resilience-project'||p.version!==1)throw Error('Unsupported project file format');if(p.checkpoint!==TunnelModelData.checkpoint_sha256)throw Error('This project uses a different model version');const x=E.validateInput(p.input),schedule=E.validateSchedule(p.schedule),T=E.checkHorizon(p.horizon);if(!Array.isArray(p.batch)||p.batch.length>5000)throw Error('Invalid batch data in the project');const batch=p.batch.map(E.validateInput);if(new Set(batch.map(x=>x.id)).size!==batch.length)throw Error('Duplicate segment IDs in the project');state.input=x;state.schedule=schedule;state.horizon=T;state.scenarioName=String(p.scenarioName||'Imported plan').slice(0,150);state.batch=batch;state.dirty=false;fillForm(x);$('#horizon').value=T;refreshAssess();refreshCompare();stageEditor();computeBatch();toast('Project opened');}
function reportHTML(){requireCurrent();const r=E.assess(state.input,E.baselineSchedule(),state.horizon),a=E.assess(state.input,state.schedule,state.horizon);const inputRows=HEADERS.map(k=>`<tr><td>${esc(({id:'Segment ID',rock_class:'Rock mass class',...E.LABELS})[k])}</td><td>${esc(state.input[k])}</td></tr>`).join('');let stageRows='';for(let i=1;i<5;i++){stageRows+=`<tr><td>DS${i}</td><td>Waiting time</td><td>${E.baselineSchedule().wait[i]}</td><td>${state.schedule.wait[i]}</td><td>—</td></tr>`;E.STAGES[i].forEach((s,k)=>stageRows+=`<tr><td>DS${i}</td><td>${esc(s[0]+' '+s[1])}</td><td>${s[2]}</td><td>${state.schedule.durations[i][k]}</td><td>${pct(s[3])}</td></tr>`);}
 return `<!doctype html><html lang="en-US"><meta charset="utf-8"><title>${esc(state.input.id)} Structural Resilience Report</title><style>body{font:14px/1.8 -apple-system,'PingFang SC',sans-serif;color:#243b4b;max-width:900px;margin:40px auto;padding:25px}h1{font-size:26px}h2{font-size:18px;margin-top:28px}table{border-collapse:collapse;width:100%;margin:16px 0;font-size:12px}td,th{border-bottom:1px solid #ddd;padding:8px;text-align:left}th{background:#f0f5f5}.metrics{padding:20px;background:#edf6f5;font-size:17px}.note{color:#657c87;font-size:12px}svg{max-width:100%}@media print{body{margin:0}tr{break-inside:avoid}h2{break-after:avoid}}</style><h1>${esc(state.input.id)} · Tunnel Structural Resilience Report</h1><p class="note">Tunnel Structural Resilience Assessment v1.1.1 · ${new Date().toLocaleString('en-US')}</p><div class="metrics">Safety factor ${fmt(r.zeta,6)}　/　DS${r.ds} ${E.NAMES[r.ds]}　/　η ${fmt(r.eta,6)}<br>Baseline resilience ${fmt(r.Rs,6)}　/ Adjusted plan ${fmt(a.Rs,6)}　/ Assessment period ${state.horizon} days</div><h2>1. Engineering Inputs</h2><table>${inputRows}</table><h2>2. Damage Probabilities and Recovery</h2><table><tr><th>State</th><th>Probability</th><th>Baseline state resilience</th><th>Adjusted state resilience</th></tr>${r.probabilities.map((p,i)=>`<tr><td>DS${i}</td><td>${pct(p)}</td><td>${fmt(r.stateResilience[i],6)}</td><td>${fmt(a.stateResilience[i],6)}</td></tr>`).join('')}</table><p>Plan: ${esc(state.scenarioName)}. The teal solid line is the baseline; the orange dashed line is the adjusted plan.</p>${recoverySVG([{points:E.history(r.probabilities,E.baselineSchedule(),state.horizon),color:'#087f84'},{points:E.history(r.probabilities,state.schedule,state.horizon),color:'#dc883c',dashed:true}],state.horizon,800,340)}<h2>3. Repair Plan Record</h2><p>Stage gains and final performance are unchanged; stages run sequentially. Durations are in days.</p><table><tr><th>State</th><th>Stage</th><th>Baseline duration</th><th>Adjusted duration</th><th>Gain fraction</th></tr>${stageRows}</table><h2>4. Method and Scope</h2><p>The point prediction uses eight engineering inputs. Damage probabilities are conditional on composite defect intensity η and weight the recovery curves. Neither directly corresponds to routine inspection ratings. Rₛ is the mean expected performance over the assessment period.</p><p>LightGBM seed 42, 900 trees; Class V rock E = 1.0 GPa. Duration comparisons retain stage gains and final recovery levels. They are not field-validated construction plans or cost-optimal solutions. Interpret results alongside inspection evidence, available resources and engineering judgement.</p><p class="note">Model checksum: ${TunnelModelData.checkpoint_sha256}</p></html>`;
}
$('#input-form').addEventListener('submit',safe(e=>{e.preventDefault();calculate();toast('Assessment complete');}));$('#input-form').addEventListener('input',()=>{updateRockLabel();state.dirty=true;$('#input-status').className='form-status dirty';$('#input-status').textContent='Inputs changed. Calculate again to update the results.';});
$$('.nav').forEach(el=>el.addEventListener('click',safe(()=>go(el.dataset.page))));$('#go-compare').addEventListener('click',safe(()=>go('compare')));
$('#load-example').addEventListener('click',safe(()=>{state.input={...TunnelExampleCases[5]};state.dirty=false;fillForm(state.input);refreshAssess();refreshCompare();toast('S06 example loaded');}));
$('#horizon').addEventListener('change',safe(()=>{try{const v=$('#horizon').value;if(!v)throw Error('Assessment period is required');state.horizon=E.checkHorizon(Number(v));refreshAssess();refreshCompare();computeBatch();}catch(e){$('#horizon').value=state.horizon;throw e;}}));
$('#apply-times').addEventListener('click',safe(()=>{
 const i=Number($('#stage-state').value),schedule=structuredClone(state.schedule),horizonValue=$('#horizon').value;
 if(!horizonValue)throw Error('Assessment period is required');const T=E.checkHorizon(Number(horizonValue));
 for(const el of $$('#stage-editor input')){if(el.value==='')throw Error('Waiting times and stage durations are required');if(el.hasAttribute('data-wait'))schedule.wait[i]=Number(el.value);else schedule.durations[i][Number(el.dataset.stage)]=Number(el.value);}
 const validated=E.validateSchedule(schedule);if(JSON.stringify(validated)!==JSON.stringify(state.schedule))state.scenarioName='Custom duration plan';
 state.schedule=validated;state.horizon=T;refreshAssess();refreshCompare();stageEditor();computeBatch();toast('Time settings applied');
}));
$('#stage-state').addEventListener('change',stageEditor);$('#stage-editor').addEventListener('change',safe(e=>{const el=e.target;if(!el.matches('input'))return;try{if(el.value==='')throw Error('Time is required');const i=Number($('#stage-state').value),copy=structuredClone(state.schedule);if(el.hasAttribute('data-wait'))copy.wait[i]=Number(el.value);else copy.durations[i][Number(el.dataset.stage)]=Number(el.value);state.schedule=E.validateSchedule(copy);state.scenarioName='Custom duration plan';refreshCompare();}catch(err){stageEditor();throw err;}}));
$('#half-wait').addEventListener('click',()=>setPreset('Halve Waiting Times',s=>s.wait=s.wait.map(v=>v*.5)));$('#short-repair').addEventListener('click',()=>setPreset('Repair durations reduced by 20%',s=>s.durations=s.durations.map(a=>a.map(v=>v*.8))));$('#case-scenario').addEventListener('click',()=>{setPreset('DS3 Duration Example',s=>s.durations[3][2]-=16.3);$('#stage-state').value='3';stageEditor();});$('#reset-plan').addEventListener('click',()=>setPreset('Same as baseline',()=>{}));
$('#example-batch').addEventListener('click',()=>{state.batch=TunnelExampleCases.map(x=>({...x}));computeBatch();toast('Loaded 20 case segments');});$('#batch-search').addEventListener('input',()=>{state.batchPage=0;renderBatch();});$('#batch-sort').addEventListener('change',()=>{state.batchPage=0;renderBatch();});$('#prev-page').addEventListener('click',()=>{state.batchPage--;renderBatch();});$('#next-page').addEventListener('click',()=>{state.batchPage++;renderBatch();});$('#batch-table').addEventListener('click',safe(e=>{const b=e.target.closest('[data-open-case]');if(!b)return;state.input={...state.batchResults[Number(b.dataset.openCase)].input};state.dirty=false;fillForm(state.input);refreshAssess();go('assess');}));
$('#template').addEventListener('click',safe(()=>download('segment-input-template.csv',E.toCSV([HEADERS,HEADERS.map(k=>TunnelExampleCases[5][k])]),'text/csv;charset=utf-8')));$('#import-batch').addEventListener('click',()=>$('#batch-file').click());$('#batch-file').addEventListener('change',safe(async e=>{const f=e.target.files[0];try{if(!f)return;if(f.size>5e6)throw Error('CSV files must not exceed 5 MB');state.batch=E.parseCSV(await f.text());computeBatch();toast('Imported  '+state.batch.length+'  segments');}finally{e.target.value='';}}));$('#export-batch').addEventListener('click',safe(exportBatch));
$('#save-project').addEventListener('click',safe(()=>download(cleanName(state.input.id)+'_resilience-project.json',JSON.stringify(project(),null,2),'application/json')));$('#load-project').addEventListener('click',()=>$('#project-file').click());$('#project-file').addEventListener('change',safe(async e=>{const f=e.target.files[0];try{if(!f)return;if(f.size>5e6)throw Error('Project file is too large');importProject(JSON.parse(await f.text()));}finally{e.target.value='';}}));$('#report').addEventListener('click',safe(()=>download(cleanName(state.input.id)+'_assessment-report.html',reportHTML(),'text/html;charset=utf-8')));
$('#export-curve').addEventListener('click',safe(()=>{requireCurrent();globalThis.TunnelPlanner?.flushEdits();const p=state.result.probabilities,b=E.baselineSchedule(),T=state.horizon,ts=[...new Set([...E.history(p,b,T),...E.history(p,state.schedule,T)].map(v=>v.t))].sort((a,b)=>a-b);const rows=[['time_d','baseline_performance','adjusted_performance'],...ts.map(t=>[t,p.reduce((a,v,i)=>a+v*E.performance(i,t,b),0),p.reduce((a,v,i)=>a+v*E.performance(i,t,state.schedule),0)])];return download(cleanName(state.input.id)+'_recovery-curve.csv',E.toCSV(rows),'text/csv;charset=utf-8');}));
$('#export-svg').addEventListener('click',safe(()=>{requireCurrent();globalThis.TunnelPlanner?.flushEdits();return download(cleanName(state.input.id)+'_recovery-curve.svg',$('#compare-chart').innerHTML,'image/svg+xml');}));
fillForm(state.input);refreshAssess();refreshCompare();stageEditor();renderBatch();
