'use strict';
(function(){
 const eng=TunnelEngine, storageKey='tunnel-resilience-project-en-v2';
 let editingState=3, planDirty=false, undo=null, restoring=false;
 let previousLocal=null;try{previousLocal=localStorage.getItem(storageKey);}catch(_e){}
 const oldStageEditor=stageEditor, oldGo=go, oldCalculate=calculate;
 const clone=x=>structuredClone(x);
 function enhanced(s){const out=eng.editableSchedule(s);if(!s.stages)out.stages.forEach((rows,i)=>rows.forEach((r,k)=>r.taskIds=TunnelStageTaskIds[i][k].slice()));return out;}
 function validateLibrary(rows){if(!Array.isArray(rows)||rows.length>500)throw Error('The library supports up to 500 tasks');const ids=new Set();return rows.map(r=>{if(!r||typeof r.id!=='string'||!/^[A-Za-z][A-Za-z0-9_-]{0,29}$/.test(r.id)||ids.has(r.id))throw Error('Task IDs must be unique and use a valid format');ids.add(r.id);if(typeof r.name!=='string'||!r.name.trim()||r.name.length>120)throw Error(r.id+'  name is required and must not exceed 120 characters');if(typeof r.duration!=='number'||!Number.isFinite(r.duration)||r.duration<0||r.duration>3650)throw Error(r.id+'  duration must be between 0 and 3650 days');return {id:r.id,name:r.name.trim(),duration:r.duration};});}
 function validateReferences(s,library){const ids=new Set(library.map(r=>r.id));for(let i=1;i<5;i++){const used=new Set();for(const row of s.stages[i])for(const id of row.taskIds){if(!ids.has(id))throw Error(`DS${i}  references an unknown task ${id}`);if(used.has(id))throw Error(`DS${i}  contains task ${id}  more than once; do not count its duration twice`);used.add(id);}}}
 function snapshot(){return {schedule:clone(state.schedule),library:clone(state.taskLibrary),name:state.scenarioName,horizon:state.horizon};}
 function remember(){undo=snapshot();$('#undo-plan').disabled=false;}
 function serialize(){return {format:'tunnel-resilience-project',version:2,modelVersion:TunnelModelData.version,checkpoint:TunnelModelData.checkpoint_sha256,input:state.input,horizon:state.horizon,schedule:state.schedule,scenarioName:state.scenarioName,batch:state.batch,taskLibrary:state.taskLibrary};}
 function autosave(){if(restoring)return;try{localStorage.setItem(storageKey,JSON.stringify(serialize()));}catch(_e){toast('Local autosave failed. Export a project file to keep your changes.',true);}}
 function refreshAll(){refreshAssess();refreshCompare();computeBatch();autosave();}
 function checkedNumber(el,label){if(!el||el.value.trim()==='')throw Error(label+' is required');const v=Number(el.value);if(!Number.isFinite(v))throw Error(label+' must be a valid number');if(el.dataset.raw!==undefined&&el.value===el.dataset.display)return Number(el.dataset.raw);return v;}
 function numberField(value,attrs){const display=Number(value.toFixed(6)).toString();return `<input type="number" step="any" value="${display}" data-raw="${value}" data-display="${display}" ${attrs}>`;}
 state.taskLibrary=clone(TunnelTaskDefaults);state.schedule=enhanced(state.schedule);
 $('#stage-state').removeEventListener('change',oldStageEditor);
 const horizonInput=$('#horizon');horizonInput.replaceWith(horizonInput.cloneNode(true));
 const apply=$('#apply-times'),replacement=apply.cloneNode(true);apply.replaceWith(replacement);
 stageEditor=function(){
  editingState=Number($('#stage-state').value);const i=editingState,s=state.schedule,rows=s.stages[i],sum=rows.reduce((a,r)=>a+r.weight,0);
  $('#stage-editor').innerHTML=`<div class="planner-controls"><label>Waiting time (days)${numberField(s.wait[i],`data-plan-wait min="0" max="3650" aria-label="DS${i} Waiting time"`)}</label><label>Final recovery level γ${numberField(s.final[i],`data-plan-final min="${eng.Q0[i]}" max="1" aria-label="DS${i} Final recovery level"`)}</label><span class="muted">Initial performance ${eng.Q0[i]} · Gain weights are normalised automatically</span></div><div class="table-wrap"><table class="planner-table"><thead><tr><th>Order</th><th>Stage name / Linked task IDs</th><th>Duration (days)</th><th>Gain weight</th><th>Gain fraction</th><th>Actions</th></tr></thead><tbody>`+rows.map((r,k)=>`<tr data-plan-row="${k}"><td>${k+1}</td><td><input data-plan-name value="${esc(r.name)}" aria-label="DS${i}  stage ${k+1} name" maxlength="120"><input class="task-ids" data-plan-ids value="${esc(r.taskIds.join(','))}" aria-label="DS${i}  stage ${k+1} linked tasks" placeholder="Comma-separated task IDs; optional"><small>${r.taskIds.length?r.taskIds.map(id=>esc((state.taskLibrary.find(t=>t.id===id)||{}).name||id)).join('; '):'Custom stage with an independent name and duration'}</small></td><td>${numberField(s.durations[i][k],`data-plan-duration min="0" max="3650" aria-label="DS${i}  stage ${k+1} duration"`)}</td><td>${numberField(r.weight,`data-plan-weight min="0" max="1000000" aria-label="DS${i}  stage ${k+1}Gain weight"`)}</td><td>${pct(sum?r.weight/sum:0)}</td><td><button class="text-button" data-plan-up="${k}" aria-label="Move up stage ${k+1}" ${k===0?'disabled':''}>↑</button><button class="text-button" data-plan-down="${k}" aria-label="Move down stage ${k+1}" ${k===rows.length-1?'disabled':''}>↓</button><button class="text-button danger" data-plan-delete="${k}" aria-label="Delete stage ${k+1}">Delete</button></td></tr>`).join('')+'</tbody></table></div><p id="stage-total" class="stage-total"></p><p id="plan-pending" class="plan-pending"></p>';
  planDirty=false;updateStageTotal();
 };
 updateStageTotal=function(){const i=Number($('#stage-state').value),dur=state.schedule.durations[i].reduce((a,b)=>a+b,0),el=$('#stage-total');if(el)el.textContent=`Total ${state.schedule.durations[i].length}  stages · Repair duration ${fmt(dur,1)}  days · Including waiting ${fmt(dur+state.schedule.wait[i],1)}  days · Final performance ${fmt(state.schedule.final[i],3)}`;};
 function commitPlan(notify=true){
  const next=clone(state.schedule),i=editingState,T=eng.checkHorizon(checkedNumber($('#horizon'),'Assessment period'));
  if($('#stage-editor [data-plan-wait]')){
   next.wait[i]=checkedNumber($('#stage-editor [data-plan-wait]'),'Waiting time');next.final[i]=checkedNumber($('#stage-editor [data-plan-final]'),'Final recovery level');
   const elements=$$('#stage-editor [data-plan-row]');if(elements.length!==next.stages[i].length)throw Error('The stage list changed. Select the damage state again.');
   elements.forEach((el,k)=>{next.stages[i][k].name=el.querySelector('[data-plan-name]').value.trim();next.stages[i][k].taskIds=el.querySelector('[data-plan-ids]').value.trim().split(/[,，、\s]+/).filter(Boolean);next.stages[i][k].weight=checkedNumber(el.querySelector('[data-plan-weight]'),'Gain weight');next.durations[i][k]=checkedNumber(el.querySelector('[data-plan-duration]'),'Stage duration');});
  }
  const valid=eng.validateSchedule(next);validateReferences(valid,state.taskLibrary);
  const changed=JSON.stringify(valid)!==JSON.stringify(state.schedule)||T!==state.horizon;
  if(changed){remember();state.schedule=valid;state.horizon=T;state.scenarioName='Custom repair plan';}
  stageEditor();refreshAll();if(notify)toast('Plan settings applied');
 }
 $('#stage-editor').addEventListener('change',e=>e.stopImmediatePropagation(),true);
 $('#stage-editor').addEventListener('input',()=>{planDirty=true;$('#plan-pending').textContent='Unapplied changes. Select Apply Plan to update gain fractions and curves.';});
 $('#horizon').addEventListener('input',()=>planDirty=true);
 replacement.addEventListener('click',safe(()=>commitPlan()));$('#apply-plan-bottom').addEventListener('click',safe(()=>commitPlan()));
 $('#stage-state').addEventListener('change',safe(()=>{const selected=$('#stage-state').value;try{if(planDirty)commitPlan(false);$('#stage-state').value=selected;stageEditor();}catch(e){$('#stage-state').value=String(editingState);throw e;}}));
 function applyNewPlan(next,label){const valid=eng.validateSchedule(next);validateReferences(valid,state.taskLibrary);remember();state.schedule=valid;state.scenarioName=label;stageEditor();refreshAll();}
 $('#stage-editor').addEventListener('click',safe(e=>{
  const b=e.target.closest('[data-plan-up],[data-plan-down],[data-plan-delete]');if(!b)return;commitPlan(false);const i=Number($('#stage-state').value),next=clone(state.schedule);
  if(b.hasAttribute('data-plan-delete')){const k=Number(b.dataset.planDelete);next.stages[i].splice(k,1);next.durations[i].splice(k,1);}
  else {const k=Number(b.dataset.planUp??b.dataset.planDown),j=k+(b.hasAttribute('data-plan-up')?-1:1);[next.stages[i][k],next.stages[i][j]]=[next.stages[i][j],next.stages[i][k]];[next.durations[i][k],next.durations[i][j]]=[next.durations[i][j],next.durations[i][k]];}
  applyNewPlan(next,'Custom repair plan');
 }));
 $('#add-stage-blank').addEventListener('click',safe(()=>{commitPlan(false);const i=Number($('#stage-state').value),next=clone(state.schedule);next.stages[i].push({name:'New repair stage',label:'Custom',weight:0,taskIds:[]});next.durations[i].push(1);applyNewPlan(next,'Custom repair plan');}));
 $('#add-stage-library').addEventListener('click',safe(()=>{commitPlan(false);const i=Number($('#stage-state').value),used=new Set(state.schedule.stages[i].flatMap(r=>r.taskIds));$('#stage-form').reset();$('#stage-task-choices').innerHTML=state.taskLibrary.map(r=>`<label><input type="checkbox" value="${r.id}" ${used.has(r.id)?'disabled':''}>${esc(r.id+' · '+r.name)} <span class="muted">${r.duration}  days${used.has(r.id)?' · Already used':''}</span></label>`).join('');$('#stage-dialog').showModal();}));
 $('#stage-form').addEventListener('submit',safe(e=>{e.preventDefault();const tasks=$$('#stage-task-choices input:checked').map(el=>state.taskLibrary.find(t=>t.id===el.value));if(!tasks.length)throw Error('Select at least one task');const i=Number($('#stage-state').value),next=clone(state.schedule),name=$('#stage-form').elements.stage_name.value.trim()||tasks.map(r=>r.name).join(' and ').slice(0,120);next.stages[i].push({name,label:'',weight:0,taskIds:tasks.map(r=>r.id)});next.durations[i].push(tasks.reduce((a,r)=>a+r.duration,0));applyNewPlan(next,'Custom repair plan');$('#stage-dialog').close();toast('Stage added. You can now edit its gain weight.');}));
 $('#sync-durations').addEventListener('click',safe(()=>{commitPlan(false);const next=clone(state.schedule);next.stages.forEach((rows,i)=>rows.forEach((r,k)=>{if(r.taskIds.length)next.durations[i][k]=r.taskIds.reduce((a,id)=>a+state.taskLibrary.find(t=>t.id===id).duration,0);}));applyNewPlan(next,'Plan with durations updated from the task library');toast('Durations updated for all stages linked to library tasks');}));
 $('#undo-plan').addEventListener('click',safe(()=>{if(!undo)return;const current=snapshot(),u=undo;state.schedule=u.schedule;state.taskLibrary=u.library;state.scenarioName=u.name;state.horizon=u.horizon;undo=current;$('#horizon').value=state.horizon;stageEditor();renderLibrary();refreshAll();toast('Last change undone. Select again to restore it.');}));
 setPreset=function(name,fn){commitPlan(false);const next=eng.baselineSchedule();fn(next);for(const t of TunnelTaskDefaults)if(!state.taskLibrary.some(r=>r.id===t.id))state.taskLibrary.push(clone(t));const plan=enhanced(next);if(name.includes('DS3')&&Math.abs(next.durations[3][2]-23.3)<1e-8)plan.stages[3][2].taskIds=plan.stages[3][2].taskIds.filter(id=>id!=='R9');applyNewPlan(plan,name);};
 function renderLibrary(){
  $('#library-count').textContent='Tasks · '+state.taskLibrary.length;$('#task-library-table').innerHTML='<table class="library-table"><thead><tr><th>Task ID</th><th>Task name</th><th>Reference duration (days)</th><th>Actions</th></tr></thead><tbody>'+state.taskLibrary.map((r,k)=>`<tr data-library-row="${k}"><td>${esc(r.id)}</td><td><input data-library-name value="${esc(r.name)}" maxlength="120" aria-label="${r.id} Task name"></td><td><input data-library-duration type="number" min="0" max="3650" step="any" value="${r.duration}" aria-label="${r.id} Reference duration"></td><td><button class="text-button danger" data-library-delete="${k}" aria-label="Delete task ${r.id}">Delete</button></td></tr>`).join('')+'</tbody></table>';
 }
 function readLibrary(){return validateLibrary($$('#task-library-table [data-library-row]').map((el,k)=>({id:state.taskLibrary[k].id,name:el.querySelector('[data-library-name]').value,duration:checkedNumber(el.querySelector('[data-library-duration]'),'Reference duration')})));}
 function flushEdits(){if(planDirty)commitPlan(false);if(state.page==='tasks'){const lib=readLibrary();validateReferences(state.schedule,lib);if(JSON.stringify(lib)!==JSON.stringify(state.taskLibrary)){remember();state.taskLibrary=lib;autosave();}}}
 $('#save-library').addEventListener('click',safe(()=>{const lib=readLibrary();validateReferences(state.schedule,lib);remember();state.taskLibrary=lib;renderLibrary();autosave();toast('Task library saved. Select Update Durations from Library to update linked stages.');}));
 $('#new-task').addEventListener('click',safe(()=>{const lib=readLibrary();if(JSON.stringify(lib)!==JSON.stringify(state.taskLibrary)){remember();state.taskLibrary=lib;autosave();}$('#task-form').reset();$('#task-dialog').showModal();}));
 $$('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).close()));
 $('#task-form').addEventListener('submit',safe(e=>{e.preventDefault();const f=$('#task-form'),lib=validateLibrary([...state.taskLibrary,{id:f.elements.task_id.value.trim(),name:f.elements.task_name.value.trim(),duration:checkedNumber(f.elements.task_duration,'Reference duration')}]);remember();state.taskLibrary=lib;renderLibrary();autosave();$('#task-dialog').close();toast('New task added to the library and available for repair plans');}));
 $('#task-library-table').addEventListener('click',safe(e=>{const b=e.target.closest('[data-library-delete]');if(!b)return;const k=Number(b.dataset.libraryDelete),lib=readLibrary(),task=lib[k];for(let i=1;i<5;i++)if(state.schedule.stages[i].some(r=>r.taskIds.includes(task.id)))throw Error(`${task.id}  is used by DS${i} ; unlink it from that damage state before deleting it`);remember();lib.splice(k,1);state.taskLibrary=lib;renderLibrary();autosave();toast('Deleted task  '+task.id);}));
 $('#export-library').addEventListener('click',safe(()=>download('repair-task-library.json',JSON.stringify({format:'tunnel-repair-library',version:1,tasks:readLibrary()},null,2),'application/json')));
 $('#import-library').addEventListener('click',()=>$('#library-file').click());$('#library-file').addEventListener('change',safe(async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2e6)throw Error('Task library files must not exceed 2 MB');const parsed=JSON.parse(await f.text());if(parsed.format!=='tunnel-repair-library'||parsed.version!==1)throw Error('Unsupported task library format');const lib=validateLibrary(parsed.tasks);validateReferences(state.schedule,lib);remember();state.taskLibrary=lib;renderLibrary();autosave();toast('Task library imported');}finally{e.target.value='';}}));
 project=function(){requireCurrent();flushEdits();return serialize();};
 importProject=function(p){
  if(p?.format!=='tunnel-resilience-project'||![1,2].includes(p.version))throw Error('Unsupported project file format');if(p.checkpoint!==TunnelModelData.checkpoint_sha256)throw Error('This project uses a different model version');
  const x=eng.validateInput(p.input),schedule=eng.validateSchedule(enhanced(p.schedule)),T=eng.checkHorizon(p.horizon),lib=validateLibrary(p.version===2?p.taskLibrary:clone(TunnelTaskDefaults));validateReferences(schedule,lib);
  if(!Array.isArray(p.batch)||p.batch.length>5000)throw Error('Invalid batch data in the project');const batch=p.batch.map(eng.validateInput);if(new Set(batch.map(x=>x.id)).size!==batch.length)throw Error('Duplicate segment IDs in the project');
  state.input=x;state.schedule=schedule;state.taskLibrary=lib;state.horizon=T;state.scenarioName=String(p.scenarioName||'Imported plan').slice(0,150);state.batch=batch;state.dirty=false;planDirty=false;undo=null;$('#undo-plan').disabled=true;fillForm(x);$('#horizon').value=T;stageEditor();renderLibrary();refreshAll();if(!restoring)toast('Project opened, including its task library and custom repair plan');
 };
 go=function(page){if(state.page==='compare'&&planDirty)commitPlan(false);if(state.page==='tasks'){const lib=readLibrary();if(JSON.stringify(lib)!==JSON.stringify(state.taskLibrary)){remember();state.taskLibrary=lib;autosave();}}oldGo(page);if(page==='tasks')renderLibrary();};
 calculate=function(){oldCalculate();autosave();};
 reportHTML=function(){
  requireCurrent();flushEdits();const b=eng.assess(state.input,eng.baselineSchedule(),state.horizon),a=eng.assess(state.input,state.schedule,state.horizon),labels={id:'Segment ID',rock_class:'Rock mass class',...eng.LABELS};let rows='';
  for(let i=1;i<5;i++){rows+=`<tr><td>DS${i}</td><td>Waiting time</td><td>${fmt(state.schedule.wait[i],3)}</td><td>—</td><td>${fmt(state.schedule.final[i],3)}</td></tr>`;eng.planStages(state.schedule,i).forEach(r=>rows+=`<tr><td>DS${i}</td><td>${esc(r[0]+' · '+r[1])}</td><td>${fmt(r[2],3)}</td><td>${pct(r[3])}</td><td>${fmt(state.schedule.final[i],3)}</td></tr>`);}
  return `<!doctype html><html lang="en-US"><meta charset="utf-8"><title>${esc(state.input.id)} Assessment Report</title><style>body{font:14px/1.8 -apple-system,'PingFang SC',sans-serif;color:#243b4b;max-width:950px;margin:40px auto;padding:25px}h1{font-size:26px}h2{font-size:18px;margin-top:28px}table{border-collapse:collapse;width:100%;margin:16px 0;font-size:12px}td,th{border-bottom:1px solid #ddd;padding:8px;text-align:left}th{background:#f0f5f5}.metrics{padding:20px;background:#edf6f5;font-size:17px}svg{max-width:100%}@media print{body{margin:0}tr{break-inside:avoid}}</style><h1>${esc(state.input.id)} · Tunnel Structural Resilience Report</h1><p>Tunnel Structural Resilience Assessment v1.1.1 · ${new Date().toLocaleString('en-US')}</p><div class="metrics">Safety factor ${fmt(b.zeta,6)}　/　DS${b.ds}　/　η ${fmt(b.eta,6)}<br>Baseline Rₛ ${fmt(b.Rs,6)}　/ Adjusted Rₛ ${fmt(a.Rs,6)}　/ Assessment period ${state.horizon} days</div><h2>Engineering Inputs</h2><table>${HEADERS.map(k=>`<tr><td>${esc(labels[k])}</td><td>${esc(state.input[k])}</td></tr>`).join('')}</table><h2>Damage Probabilities and Recovery</h2><table><tr><th>State</th><th>Probability</th><th>Baseline state resilience</th><th>Adjusted state resilience</th></tr>${b.probabilities.map((p,i)=>`<tr><td>DS${i}</td><td>${pct(p)}</td><td>${fmt(b.stateResilience[i],6)}</td><td>${fmt(a.stateResilience[i],6)}</td></tr>`).join('')}</table><p>${esc(state.scenarioName)}. The teal solid line is the baseline; the orange dashed line is the adjusted plan.</p>${recoverySVG([{points:eng.history(b.probabilities,eng.baselineSchedule(),state.horizon),color:'#087f84'},{points:eng.history(a.probabilities,state.schedule,state.horizon),color:'#dc883c',dashed:true}],state.horizon,800,340)}<h2>Adjusted Plan Details</h2><p>Stages run in the listed order. Gain weights are normalised to fractions. Each performance increment equals (final minus initial performance) × gain fraction. Initial performance for DS1–DS4 is 0.9, 0.75, 0.25 and 0, respectively.</p><table><tr><th>State</th><th>Stage</th><th>Duration / days</th><th>Gain fraction</th><th>Final performance</th></tr>${rows}</table><h2>Task Library Record</h2><table><tr><th>ID</th><th> name</th><th>Reference duration / days</th></tr>${state.taskLibrary.map(t=>`<tr><td>${esc(t.id)}</td><td>${esc(t.name)}</td><td>${t.duration}</td></tr>`).join('')}</table><h2>Scope of Use</h2><p>The point prediction uses eight engineering inputs. Probabilities are conditional on η and weight the recovery curves. Model damage states are distinct from routine inspection ratings. Custom tasks, durations and recovery effects must be determined for the relevant site conditions.</p><p>Model identifier: ${TunnelModelData.checkpoint_sha256}</p></html>`;
 };
 stageEditor();renderLibrary();
 if(previousLocal){try{restoring=true;importProject(JSON.parse(previousLocal));restoring=false;toast('Saved project and task library restored');}catch(e){restoring=false;toast('Unable to restore local settings. Open a project backup: '+e.message,true);}}
 refreshAll();
 globalThis.TunnelPlanner={validateLibrary,validateReferences,enhanced,serialize,commitPlan,flushEdits};
})();
